version = 1

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
max_line_length = 120

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"
